### ISSUE TITLE
moveItemEvent fails when having an array of objects

### ISSUE THREAD

**Issue by zalmoxisus** [redexp/simple-diff#1]
First, thanks a lot for working on this! After trying other diff libraries, I found yours being very simple and useful.

Here's an issue. For example:

``` js
diff(
      [{ a: 1 }, { a: 2 }],
      [{ a: 1 }, { a: 2 }]
)
```

will return:

``` js
[ { oldPath: [],
    newPath: [],
    type: 'move-item',
    oldIndex: 1,
    curIndex: 1,
    newIndex: 0 },
  { oldPath: [ 1, 'a' ],
    newPath: [ 0, 'a' ],
    type: 'change',
    oldValue: 2,
    newValue: 1 },
  { oldPath: [],
    newPath: [],
    type: 'move-item',
    oldIndex: 1,
    curIndex: 0,
    newIndex: 1 } ]
```

Also maybe to add an option to disable catching moveItemEvent at all, as for some cases one should want to consider `[0, 1] -> [1, 0]` as changeEvent.

**Comment by redexp** [comment]
One of idea of this lib that all arrays should have uniq id in their items. If you add an option `idProp: 'a'` then `diff` will not find any changes.

``` javascript
diff(
      [{ a: 1 }, { a: 2 }],
      [{ a: 1 }, { a: 2 }],
      {idProp: 'a'}
)
```

For second question, you can add option `callback:` and just skip `move-item` events

``` javascript
function nonMoveDiff(a, b, ops) {
  var changes = [];

  diff(a, b, extend({}, ops, {
    callback: function (e) {
      if (e.type !== 'move-item') {
        changes.push(e);
      }
      // or
      if (e.type === 'move-item') {
        e.type = 'change';
      }
      changes.push(e);
    }
  }));

  return changes;
}
```

**Comment by zalmoxisus** [comment]
@redexp, thanks for the prompt replay. It could be a solution. I was investigating to use the lib to generate more meaningful tests for [`redux-devtools-extension`](https://github.com/zalmoxisus/redux-devtools-extension). [We are comparing the full state objects now](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.2.0), which is not practical. Thanks to your lib we could compare only the changes, which works amazing except for `move-item`. That said, in our case we don't know which would be `idProp`.

As for `nonMoveDiff`, maybe I'm missing something, but don't see how we'll get `newValue` from there.

**Comment by redexp** [comment]
For now the only way I see is to create cache with copy of array and on each move event you will modify this array and push to changes event `change` with this array as `newValue` like

``` javascript
function moveToChangeDiff(a, b, ops) {
    var changes = [],
        cache = {};

    diff(a, b, extend({}, ops, {
        callback: function (e) {
            if (e.type === 'move-item') {
                var path = e.oldPath.map(numbersToAsterisk).join('.'),
                    array = cache[path];

                if (!array) {
                    cache[path] = array = get(a, e.oldPath);
                }

                e.type = 'change';
                e.oldValue = array;
                e.newValue = moveItem(clone(array), e.curIndex, e.newIndex);

                cache[path] = e.newValue;
            }

            changes.push(e);
        }
    }));

    return changes;
}
```

not tried this code but I think you get an idea

**Comment by redexp** [comment]
If you don't know `idProp` then I can add feature to lib to compare arrays as is, means it will compare one by one and if new array is bigger then you will get `add-item` if smaller then `remove-item` and you will not get `move-item` at all. How about to use `idProp: '*'` to turn on this mode?

**Comment by zalmoxisus** [comment]
Using `idProp: '*'` would be great!

Thanks for the detailed response!

**Comment by redexp** [comment]
try v1.3.0

**Comment by zalmoxisus** [comment]
@redexp, Perfect! thanks a lot!
