### ISSUE TITLE
Dates are ignored

### ISSUE THREAD

**Issue by vbgm** [redexp/simple-diff#3]
```
  const oldItem = { someDate: new Date() };
  console.log('oldItem', oldItem);

  const newItem = { someDate: new Date(2017, 1, 1) };
  console.log('newItem', newItem);

  const test = diff(oldItem, newItem);
  console.log('test', test);

```
outputs:

```
oldItem { someDate: Tue Feb 14 2017 14:55:13 GMT+0100 (CET) }
newItem { someDate: Sun Jan 01 2017 00:00:00 GMT+0100 (CET) }
test []
```

**Comment by redexp** [comment]
You expect that result will be like this?
```
    [{
        oldPath: ['someDate'],
        newPath: ['someDate'],
        type: 'change',
        oldValue: Tue Feb 14 2017 14:55:13 GMT+0100 (CET),
        newValue: Sun Jan 01 2017 00:00:00 GMT+0100 (CET)
    }]
```
For `diff` Date object is simple empty object without any properties because Date object do not have own properties. Maybe it will be more safe if you convert Date object to UTC string?

**Comment by vbgm** [comment]
Thanks for quick feedback @redexp. Yes, what you say looks logical. I am about to find a workaround to work with UTC string (might require double conversion), it is just it could be more tidy if this could work out of the box.

**Comment by redexp** [comment]
Than we should decide how and when compare two "empty" objects? Maybe some kind of plugins, so you can define your own handler of any class? Like this
```javascript
diff.define(Date, function (oldDate, newDate) {
  return oldDate.toString() === newDate.toString();
});
```

**Comment by vbgm** [comment]
I use underscore throughout the project but that would be too heavy for simple-diff.. maybe some single lodash function? ..about to check options now and come back.

**Comment by redexp** [comment]
Don't understand about underscore and lodash, I know those libs, but what you mean by " that would be too heavy"?

**Comment by vbgm** [comment]
:-) If I understand you correctly you wanted to find a 'plugin' to compare dates (please clarify if it is not the case) Since I did not work with dates extensively I thought that either underscore or lodash could potentially help. For example _.isDate() is technically could be a good filter to distinguish between an object and a date.. But maybe I did not understand you initially with the code example.

**Comment by vbgm** [comment]
and when I meant 'heavy' it is just not to have dependency on a huge library because of the single function.. :-)

**Comment by redexp** [comment]
By `plugin` I mean add ability to define class which objects should be compared not by default (by properties) but by custom function which should return `true` if they equal and `false` if not.

**Comment by vbgm** [comment]
Ah, got it. Sounds smart. And then the code example of dates comparison that you wrote makes sense. Since I am about to integrate simple-diff to my project now (and since you are super quick with feedbacks) let me know if I could help you with something here.

**Comment by vbgm** [comment]
Okay, I have read some more info about the dates formats in general and formats in which MongoDB stores the dates, so in my specific case I see no reason to compare the objects, but can easily compare the strings instead (which I have tested works just fine - just remove the 'new' from the Date()) in the first example above. However the 'plugin' which you mentioned might be helpful as well in some special cases.

**Comment by vbgm** [comment]
..I was too fast with the answer, in real project (not in test) still have to perform double conversion manually, so the initial problem exists.

**Comment by redexp** [comment]
ok, I will add this functionality in a few days. Only one question, how to call this method? `define()`, `plugin()`, `registerObjectComparator()` ...

**Comment by vbgm** [comment]
I would say the simpler the better. Overall I liked your logic of naming things in simple-diff, like oldValue -> newValue. So, out of the three, the registerObjectComparator seem to be the worst. But the 'define' and 'plugin' sound also not the best. 

Since with this functionality we are actually comparing the objects why not to name the function just 'compare' (other variant might be 'match')? For example:

```
diff.compare(Date, function (oldDate, newDate) {
  return oldDate.toString() === newDate.toString();
});

diff.compare(Number, function (oldNumber, newNumber) {
  return oldNumber.toFixed(1) === newNumber.toFixed(1);
});

diff.compare(String, function (oldString, newString) {
  if (oldString.length < 50 && newString < 50) {
    return oldString === newString;
  } else {
    return areComplexStringsEqual(oldString, newString);
  }
});
```

Actually this syntax could be in line with something like this:

```
diff.addProp('delta', function(oldString, newString) {
  return getDelta(oldString, newString);
});
```


But having said all this (which is a nice functionality to have of course) I dont get it why you dont want to simply convert the dates to strings internally?

**Comment by redexp** [comment]
> I dont get it why you dont want to simply convert the dates to strings internally?

Because after Date somebody will need to compare RegExp, and after that Element and so on.

I don't like `compare()`, for me `addComparator()` sounds more understandable

**Comment by vbgm** [comment]
I understand. Then the only alternative could be `addMatcher()`. Even though in English the word 'matcher' does not directly fit the meaning of the function, for someone it might sound better than 'com-pa-ra-tor'.

> Because after Date somebody will need to compare RegExp

But maybe it makes sense to integrate 'standard' things in a standard way and add the matchers/comparators for very special cases? Even RegExp can be stringified and compared, as well as Dates. There might be an option, like { stringify: true } to convert every object that has toString() function within.

**Comment by vbgm** [comment]
Double checked..  addComparator is better than addMatcher. It is just hopefully we don't need to write it on every occasion to compare standard things like Dates.. ;-)

**Comment by redexp** [comment]
Well we can create matchers/comparators for all standart classes, but I think in most cases users will not have Date's and anything like that and checking everytime every object on `instanceof` list of classes will be overhead. When user need some special comparsion he will add it to his project.

**Comment by vbgm** [comment]
At the end it is up to you. In my realistic scenario as a user of simple-diff, when a change of a MongoDB document occurs, I compare the new changed document with an old one and save the difference in a separate collection/document. And within all my collections (about 10 for now) **_every_** collection schema (and therefore every document) has 'createdAt' date field. Many have at least two date fields, like 'updatedAt'. So it means that the Date is used very often compared to the hypothetical 'every object of `instanceof`'.

**Comment by zalmoxisus** [comment]
Maybe instead of adding a comparator, we'd better just add a custom `objectHash` for the current comparator:
```js
var changes = diff(oldObject, newObject, {
    idProp: 'id',
    objectHash: function (obj) { return obj instanceof Date ? obj.toString() : obj }
});
```

It could be `getHash`, though using the same method as [`jsondiffpatch`](https://github.com/benjamine/jsondiffpatch) would be easer for understanding and migration.

**Comment by redexp** [comment]
@zalmoxisus and what should be in `oldValue`/`newValue` - Date or String?

**Comment by zalmoxisus** [comment]
@redexp for my use case transforming Date to a string wouldn't be a problem, but for many others it could be. I guess we should return the original data and use `objectHash` just for comparison.

**Comment by redexp** [comment]
As for me `addComparator` is more customizable because you can compare objects in different way. With `objectHash` you have only one way to convert objects to string or number

**Comment by redexp** [comment]
@zalmoxisus hey, with comparator we can solv problem with circular referenses. We just need to add some extra info so you can run through all parents and figureout is it c.r. or not.

**Comment by zalmoxisus** [comment]
@redexp, that makes sense, then go with the `addComparator`.

BTW, why we have to stringify dates? Isn't possible just to compare them as is?
```js
var d1 = new Date();
var d2 = d1;
var d3 = new Date();

console.log(d1 === d2, d1 !== d3);
```

**Comment by redexp** [comment]
@zalmoxisus it would be wrong to compare by objects links here code
```javascript
var d1 = new Date(), d2 = new Date();
console.log(d1 === d2); // false
console.log(d1.toString() === d2.toString()); // true
```

**Comment by redexp** [comment]
instead of `addComparator` I added `comparators:` option, enjoy )
