### ISSUE TITLE
Unexpected diff when adding to and reordering array

### ISSUE THREAD

**Issue by jwm01cg** [redexp/simple-diff#5]
Hi, thank you for making this library. I have been using it with arrays of objects and I encountered a result that doesn't really make sense to me. Here's a minimal reproducible example:

```js
const simpleDiff = require('simple-diff')

const oldObject = {
  array: [
    {
      id: '1',
    },
    {
      id: '2',
    },
    {
      id: '3',
    },
  ],
};

const newObject = {
  array: [
    {
      id: '4',
    },
    {
      id: '2',
    },
    {
      id: '3',
    },
    {
      id: '1',
    },
  ],
};

var changes = simpleDiff(oldObject, newObject, {});

console.log(changes);
```

Essentially, I have moved `id: '1'` to the end of the list, and inserted a new item at the start with `id: '4'`.
On v1.7.2, I get this output:

```js
[
  {
    oldPath: [ 'array' ],
    newPath: [ 'array' ],
    type: 'add-item',
    oldIndex: -1,
    curIndex: -1,
    newIndex: 0,
    newValue: { id: '4' }
  },
  {
    oldPath: [ 'array' ],
    newPath: [ 'array' ],
    type: 'move-item',
    oldIndex: 1,
    curIndex: 2,
    newIndex: 1
  },
  {
    oldPath: [ 'array' ],
    newPath: [ 'array' ],
    type: 'move-item',
    oldIndex: 2,
    curIndex: 3,
    newIndex: 2
  }
]
```

The `add-item` entry is fine, but I am confused about the two `move-item` entries as they have equal values for `oldIndex` and `newIndex`, which suggests they weren't moved? I am also not sure what `curIndex` is meant to represent. Lastly there is no `move-item` entry with `oldIndex: 0` and `newIndex: 3` that represents `id: '1'` being moved.

This is the diff I would expect from my example:

```js
[
  {
    oldPath: [ 'array' ],
    newPath: [ 'array' ],
    type: 'add-item',
    oldIndex: -1,
    curIndex: -1,
    newIndex: 0,
    newValue: { id: '4' }
  },
  {
    oldPath: [ 'array' ],
    newPath: [ 'array' ],
    type: 'move-item',
    oldIndex: 0,
    curIndex: 1,
    newIndex: 3
  }
]
```

Maybe I am misunderstanding the original diff - in particular if I can use `curIndex` to work out what I want somehow? Thanks in advance for any help you can give.

**Comment by redexp** [comment]
Hello. I've already thought about this problem and I couldn't come up with an elegant solution. But diff with 3 steps is still correct
So we have `1, 2, 3` -> `4, 2, 3, 1`. 

1. add 4 `newIndex: 0` -> `4, 1, 2, 3` (and here lib comparing with `4, 2, 3, 1` and see that after 4 goes 2)
2. move 2 which `curIndex: 2` (after step 1) or `oldIndex: 1` (from origin array) to `newIndex: 1` -> `4, 2, 1, 3`
3. move 3 which `curIndex: 3` (after step 2) or `oldIndex: 2` (from origin array) to `newIndex: 2` -> `4, 2, 3, 1`

I understand that you as a human see that easier just move 1 to the end, but if this was array with 100 items then you as human can't be sure is it just 1 should be moved to the end and nothing changed in between. You will go through hole array and compare each item. Even if I come up with some solution I still not sure - maybe it will just slow down most of situations 

I'll closing this issue for now/ If diff with 3 steps still not clear for you then I'll try to explain it one more time

**Comment by jwm01cg** [comment]
Thank you for the explanation. It makes sense now that I know what `curIndex` is, I wasn't really getting what that meant. And I appreciate it's difficult to produce diffs that make sense, as there's no way for me to tell the library what the 'intent' behind the changes was (I see this problem with git quite often).

I did a hack here which gave me the diff I wanted:

https://github.com/redexp/simple-diff/blob/master/simple-diff.js#L165

```diff
- if (i !== curIndex)
+ if (i !== curIndex && i !== oldIndex)
```

but that does make some of your tests fail which were producing these diffs with `oldIndex` == `newIndex`, so I'm not sure if it's an acceptable solution. And I am not sure how it would behave with 100 items as you say. 

Happy for this to stay closed if you don't think the above change should be made.
